spring:
  application:
    name: jpa-test-service
  datasource:
    //url: "jdbc:sqlserver://localhost:1433;databaseName=vurdering;encrypt=false"
    //username: SA
    //password: Compose11234#
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changes.xml
logging:
  level:
    org.hibernate.SQL: DEBUG